let
    ReplaceCountryCodes = [
        CN = "China",
        TW = "Taiwan",
        GB = "United Kingdom",
        FR = "France",
        DE = "Germany",
        SE = "Sweden",
        MA = "Morocco",
        FI = "Finland",
        US = "United States",
        BR = "Brazil",
        CH = "Switzerland",
        AT = "Austria",
        IN = "India",
        ID = "Indonesia",
        EE = "Estonia",
        SI = "Slovenia",
        PL = "Poland",
        SG = "Singapore",
        IT = "Italy",
        IE = "Ireland",
        BE = "Belgium",
        TN = "Tunisia",
        MY = "Malaysia",
        HU = "Hungary",
        MX = "Mexico",
        XQ = "Unknown",
        CZ = "Czech Republic",
        TH = "Thailand",
        XN = "Unknown",
        XO = "Unknown",
        JP = "Japan",
        HK = "Hong Kong",
        XC = "Unknown",
        KN = "Saint Kitts and Nevis",
        XA = "Unknown",
        KR = "South Korea",
        DK = "Denmark",
        XM = "Unknown",
        PE = "Peru",
        CL = "Chile",
        CO = "Colombia",
        GT = "Guatemala",
        AR = "Argentina",
        TR = "Turkey",
        SA = "Saudi Arabia",
        KW = "Kuwait",
        AU = "Australia",
        VE = "Venezuela",
        NG = "Nigeria",
        ZA = "South Africa",
        AE = "United Arab Emirates",
        TT = "Trinidad and Tobago",
        PR = "Puerto Rico",
        PH = "Philippines",
        NL = "Netherlands",
        SK = "Slovakia",
        PK = "Pakistan",
        QA = "Qatar",
        EG = "Egypt",
        AO = "Angola",
        OM = "Oman",
        CA = "Canada",
        IQ = "Iraq",
        UY = "Uruguay",
        LK = "Sri Lanka",
        ES = "Spain",
        CM = "Cameroon",
        DO = "Dominican Republic",
        BH = "Bahrain",
        NZ = "New Zealand",
        GR = "Greece",
        BO = "Bolivia",
        MO = "Macau",
        VN = "Vietnam"
    ],

    ReplaceCodes = Table.ReplaceValue(
        #"Changed Type4", 
        each [Country of Ultimate Destination Code], 
        each Record.FieldOrDefault(ReplaceCountryCodes, [Country of Ultimate Destination Code], [Country of Ultimate Destination Code]),
        Replacer.ReplaceValue,
        {"Country of Ultimate Destination Code"}
    )
in
    ReplaceCodes
